import { BEAT } from "../constants";

// Sound cue sheet. Every cue is anchored to the master frame sheet so music
// and effects stay locked to picture. To replace any sound, drop a new file
// with the same name into public/last-spin/audio/ (or change `file` here).
// All files are original and generated by scripts/last-spin/generate-audio.mjs.

export type Cue = {
  name: string;
  file: string;
  from: number; // absolute frame
  durationInFrames?: number;
  volume: number;
  fadeOut?: number; // frames of fade at the end of durationInFrames
};

export const MUSIC: Cue[] = [
  // Playful/tense encounter -> warm bloom during the spin
  { name: "Music: encounter & spin", file: "music-1-encounter-spin.wav", from: 0, durationInFrames: 222, volume: 0.62, fadeOut: 12 },
  // Silly -> nostalgic -> heroic. The file hard-stops at exactly 7.0 s (frame 420).
  { name: "Music: fantasy", file: "music-2-fantasy.wav", from: BEAT.fantasyStart, durationInFrames: 210, volume: 0.7 },
  // Sparse melancholic piano for the empty battlefield and the last memory
  { name: "Music: piano", file: "music-3-piano.wav", from: BEAT.pianoStart, volume: 0.75 },
];

export const SFX: Cue[] = [
  { name: "Bandit shot 1", file: "sfx-bandit-shot.wav", from: BEAT.banditVolley1, volume: 0.45 },
  { name: "Bandit shot 2", file: "sfx-bandit-shot.wav", from: BEAT.banditVolley1 + 3, volume: 0.4 },
  { name: "Hit 1", file: "sfx-hit.wav", from: BEAT.banditHit1, volume: 0.55 },
  { name: "Shelly step", file: "sfx-step.wav", from: 30, volume: 0.3 },
  { name: "Shelly step", file: "sfx-step.wav", from: 40, volume: 0.3 },
  { name: "Shelly shoots bandit", file: "sfx-shotgun.wav", from: BEAT.shellyShootsBandit, volume: 0.45 },
  { name: "Pump", file: "sfx-pump.wav", from: 62, volume: 0.35 },
  { name: "Bandit parting shot 1", file: "sfx-bandit-shot.wav", from: BEAT.banditParting, volume: 0.4 },
  { name: "Bandit parting shot 2", file: "sfx-bandit-shot.wav", from: BEAT.banditParting + 3, volume: 0.35 },
  { name: "Hit 2", file: "sfx-hit.wav", from: BEAT.banditHit2, volume: 0.55 },
  { name: "Shelly spins", file: "sfx-spin.wav", from: BEAT.shellySpinStart, volume: 0.4 },
  { name: "El Primo surprised", file: "sfx-surprise.wav", from: BEAT.primoSurprise, volume: 0.5 },
  { name: "El Primo spins", file: "sfx-spin.wav", from: BEAT.primoSpinStart, volume: 0.5 },
  { name: "Heart Pin", file: "sfx-pin-pop.wav", from: BEAT.heartPin, volume: 0.6 },
  { name: "Shelly Pin", file: "sfx-pin-pop.wav", from: BEAT.shellyPin, volume: 0.45 },
  { name: "Into the dream", file: "sfx-dream.wav", from: BEAT.vortexStart, volume: 0.55 },
  { name: "Silly jump", file: "sfx-slide-whistle.wav", from: 240, volume: 0.45 },
  { name: "Propeller sputters", file: "sfx-sputter.wav", from: 316, volume: 0.5 },
  { name: "Heroic leap", file: "sfx-hero-leap.wav", from: 380, volume: 0.5 },
  // --- the betrayal ---
  { name: "BANG", file: "sfx-shotgun.wav", from: BEAT.bang, volume: 1 },
  { name: "Hit (betrayal)", file: "sfx-hit.wav", from: BEAT.bang + 1, volume: 0.7 },
  { name: "Tension", file: "sfx-tension.wav", from: BEAT.bang + 2, durationInFrames: BEAT.superFire - BEAT.bang - 2, volume: 0.35 },
  { name: "Pump (betrayal)", file: "sfx-pump.wav", from: 428, volume: 0.45 },
  { name: "Super ready", file: "sfx-super-ready.wav", from: BEAT.superReadyCue, volume: 0.85 },
  { name: "Super blast", file: "sfx-super-blast.wav", from: BEAT.superFire, volume: 1 },
  { name: "Wall breaks", file: "sfx-wall-break.wav", from: BEAT.superHit + 1, volume: 0.6 },
  { name: "Defeat", file: "sfx-defeat.wav", from: BEAT.primoPoof, volume: 0.4 },
  { name: "Cube drops", file: "sfx-cube-drop.wav", from: BEAT.cubeDrop, volume: 0.3 },
  { name: "Wind", file: "sfx-wind.wav", from: 480, volume: 0.22 },
  { name: "Pump (after)", file: "sfx-pump.wav", from: 476, volume: 0.25 },
  { name: "Shelly step", file: "sfx-step.wav", from: 522, volume: 0.22 },
  { name: "Shelly step", file: "sfx-step.wav", from: 536, volume: 0.22 },
  { name: "Shelly step", file: "sfx-step.wav", from: 550, volume: 0.22 },
  { name: "Cube pickup", file: "sfx-cube-pickup.wav", from: BEAT.shellyReachCube, volume: 0.28 },
  { name: "Shelly step", file: "sfx-step.wav", from: 590, volume: 0.18 },
  { name: "Shelly step", file: "sfx-step.wav", from: 606, volume: 0.15 },
  { name: "Shelly step", file: "sfx-step.wav", from: 622, volume: 0.12 },
  { name: "Shelly step", file: "sfx-step.wav", from: 638, volume: 0.08 },
];
